data<-read.table("household_power_consumption.txt", sep=";", header=TRUE, stringsAsFactors=FALSE)
data$Date<-as.Date(data$Date, format="%d/%m/%Y")
data2<-subset(data, Date=="2007-02-01")
data3<-subset(data, Date=="2007-02-02")
data4<-rbind(data2, data3)
data4$Global_active_power<-as.numeric(data4$Global_active_power)
x<-paste(data4$Date, data4$Time)
x<-strptime(x, "%Y-%m-%d %H:%M:%S")
y<-weekdays(x, abbreviate=TRUE)
data5<-cbind(y,x,data4)
data5$Sub_metering_1<-as.numeric(data5$Sub_metering_1)
data5$Sub_metering_2<-as.numeric(data5$Sub_metering_2)
data5$Sub_metering_3<-as.numeric(data5$Sub_metering_3)
png(filename="plot3.png", width = 480, height = 480)
plot(data5$x, data5$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering", col="black")
lines(data5$x, data5$Sub_metering_2, type="l", xlab="", col="red")
lines(data5$x, data5$Sub_metering_3, type="l", xlab="", col="blue")
legend( x="topright", legend=c("Sub_metering_1","Sub_metering_2", "Sub_metering_3"), col=c("black", "red","blue"), lwd=1)
dev.off()