data<-read.table("household_power_consumption.txt", sep=";", header=TRUE, stringsAsFactors=FALSE)
data$Date<-as.Date(data$Date, format="%d/%m/%Y")
data2<-subset(data, Date=="2007-02-01")
data3<-subset(data, Date=="2007-02-02")
data4<-rbind(data2, data3)
data4$Global_active_power<-as.numeric(data4$Global_active_power)
x<-paste(data4$Date, data4$Time)
x<-strptime(x, "%Y-%m-%d %H:%M:%S")
y<-weekdays(x, abbreviate=TRUE)
data5<-cbind(y,x,data4)
png(filename="plot2.png", width = 480, height = 480)
plot(data5$x, data5$Global_active_power, type="l", xlab="", ylab="Global Active Power (kilowatts)")
dev.off()