data<-read.table("household_power_consumption.txt", sep=";", header=TRUE, stringsAsFactors=FALSE)
data$Date<-as.Date(data$Date, format="%d/%m/%Y")
data2<-subset(data, Date=="2007-02-01")
data3<-subset(data, Date=="2007-02-02")
data4<-rbind(data2, data3)
data4$Global_active_power<-as.numeric(data4$Global_active_power)
png(filename="plot1.png", width = 480, height = 480)
hist(data4$Global_active_power, main="Global Active Power", xlab="Global Active Power (kilowatts)", col="red")
dev.off()
